### ISSUE TITLE
Demultiplexing Part 2 Peer Review

### ISSUE THREAD

**Issue by AnnaGraceWelch** [aw-watson/Demultiplex#1]
`If either index is not in our list of indices OR the average quality score for either index is below a chosen threshold:`

It may be useful to first check if there is an N present in either of the indices. This implementation will still catch that it is an unknown index and therefore output it into the correct file, but it will likely take longer since it has to check against each known index . Since the files we are looking at are so large, this may be something to consider to potentially speed up the process. 

Additionally, you may want to implement a function to average the quality scores for each index since you will be calling it for each record. I don't think you summed all the quality scores in each sequence either yet, so you may want to add that as well in order to get your averages to compare to your cutoff. 

`Open each of the 52 output files to write to.`

Theoretically, since you are implementing a quality cutoff, you could end up with less than 52 files if all of one index pair's reads are too low quality (probably unlikely this would happen). But, maybe consider whether you want to create these files before you start reading the records, or if you want to create them as the pairs appear in the file. I think an argument could be made for both, so just something to think about. 

`Read one record at a time from each input file, storing in appropriate lists.`

How will you read each line and store it in the appropriate index of your list? Will you use something like readline() or something else? I do like the idea of storing each file record into the appropriate four item list (for R1, R2, R3, and R4), as it will make it fairly easy to then organize this information to amend the header and output it to a file. 

Make sure to empty your lists after each record too!

`Go over the dictionary of mismatched index pairs.`
`Go over the dictionary of matching index pairs.`

I like your implementation of two separate dictionaries that are incremented and then used to write to a TSV file. It keeps this abundance of information very well organized within your code, which I think will help tremendously when troubleshooting any issues. 

Overall, your pseudocode was written very clear and concise to be able to tackle the problem. If I misinterpreted anything you had written, apologies! I really think you did a great job!

**Comment by aw-watson** [comment]
Thanks for the feedback! I'll go point-by-point.

-Checking for N base calls: it'll actually be faster (while maintaining correctness) if we just check if the index is in a dictionary of our known indices (O(1)). I'll update the wording, see also  #4.

-Averaging quality scores: I'll add a function definition. See also #5.

-Output file strategy: I prefer not to be unpredictably opening files based on some condition in the middle of a loop. However, in situations where no records end up in the files corresponding to that index code, I think those files should be cleaned up, see #6.

-Line reading and storage: I'll update the wording to make it more clear that I'm consuming one line at a time, and doing that 4 times for each of the input files, but I want to stick to the feedback from course staff to avoid getting too code-like in this outline.

-Emptying lists: not necessary. Replacing the contents of the lists with the new records at the top of the loop is fine.

**Comment by aw-watson** [comment]
All issues resolved!
